// Generated by https://quicktype.io

export interface Offers {
  creationDate:            string;
  deliveryCutOffTimeEpoch: string;
  deliveryRequest:         string;
  endTime:                 number;
  expirationDate:          number;
  hidden:                  boolean;
  isPriorityOffer:         boolean;
  legalEntity:             string;
  maxWorkload:             number;
  offerId:                 string;
  offerMetadata:           string;
  offerType:               string;
  rateInfo:                RateInfo;
  schedulingType:          string;
  serviceAreaId:           string;
  serviceTypeId:           string;
  serviceTypeMetadata:     ServiceTypeMetadata;
  startTime:               number;
  startingLocation:        StartingLocation;
  status:                  string;
  trIds:                   string;
}

export interface RateInfo {
  PriceDetails:     string;
  currency:         string;
  isSurge:          boolean;
  priceAmount:      number;
  pricingUXVersion: string;
  projectedTips:    number;
  surgeMultiplier:  string;
  tipPresentation:  string;
}

export interface ServiceTypeMetadata {
  modeOfTransportation: string;
  nameClassification:   string;
}

export interface StartingLocation {
  address:              Address;
  geocode:              Geocode;
  locationType:         string;
  startingLocationName: string;
}

export interface Address {
  address1:    string;
  address2:    string;
  address3:    string;
  addressId:   string;
  city:        string;
  countryCode: string;
  name:        string;
  phone:       string;
  postalCode:  string;
  state:       string;
}

export interface Geocode {
  latitude:  number;
  longitude: number;
}

export interface WareHouse {
  serviceAreaId: string;
  serviceAreaName: string;
}
